### ISSUE TITLE
Bug in the upload of CSV files 

### ISSUE THREAD

**Issue by gschwend** [linea-it/pz-server#119]
The upload is not concluded even though the progress bar shows 100%

test files are available here (restricted access):

https://drive.google.com/drive/folders/1oJLqpLfJ0loqThpfaw-akSWMYgmoIGo1?usp=sharing

**Comment by glaubervila** [comment]
@gschwend Acredito que o problema era relacionado ao /archive a mesma causa do problema com banco de dados. 
@crisingulani Testou alterando os pontos de montagem do ambiente para uma pasta local na srvnode04 fora do /archive e parece que o problema foi resolvido. Este problema com o /archive gerou o problema com o banco de dados o upload e download dos arquivos, basicamente tudo que tinha relação com escrever/ler do /archive. 
Acredito que essa issue pode ser considerada Done ou invalida.

**Comment by gschwend** [comment]
movi para in progress enquanto estou testando
