### ISSUE TITLE
Bug in download

### ISSUE THREAD

**Issue by gschwend** [linea-it/pz-server#122]
The download button is not working for data products with multiple files. 

Example: 
https://pz-server-dev.linea.org.br/product/simple_training_set_Uch3wIA 

For single files it works. 

Example:
https://pz-server-dev.linea.org.br/product/gama_specz_subsample_sE-ki_Y

**Comment by glaubervila** [comment]
@gschwend Acredito que o problema era relacionado ao /archive a mesma causa do problema com banco de dados. 
@crisingulani Testou alterando os pontos de montagem do ambiente para uma pasta local na srvnode04 fora do /archive e parece que o problema foi resolvido. Este problema com o /archive gerou o problema com o banco de dados o upload e download dos arquivos, basicamente tudo que tinha relação com escrever/ler do /archive. 
Acredito que essa issue pode ser considerada Done ou invalida.
