### ISSUE TITLE
Filter by product type in product list

### ISSUE THREAD

**Issue by glaubervila** [linea-it/pz-server#64]
Testei o Filtro por product type e não está funcionando corretamente.

Investiguei o erro e o problema é que o filtro não está mais funcionando por id, acredito que seja conflito com a função _icontains. 

minha sugestão é manter o filtro product_type como o default do django e criar um novo para filtrar por nome. 
e alterar o  local onde é usado o filtro por nome para  usar o novo filtro. 

```
class ProductFilter(filters.FilterSet):
    release__isnull = filters.BooleanFilter(field_name="release", lookup_expr="isnull")
    uploaded_by__or = filters.CharFilter(method="filter_user")
    uploaded_by = filters.CharFilter(method="filter_user")
    product_type_name__or = filters.CharFilter(method="filter_product_type")
    product_type_name = filters.CharFilter(method="filter_product_type")
```

**Comment by Gschwend** [comment]
@crisingulani eu testei agora na interface e funcionou. Posso fechar o issue?

**Comment by Gschwend** [comment]
Corrigido.
